### ISSUE TITLE
Hijri Calenar Offest

### ISSUE THREAD

**Issue by osamasaleh90** [kbwood/calendars#28]
cannot change day number if hijri doesn't match gregorian calendar

**Comment by kbwood** [comment]
I don't understand what you mean. How does the Hijri calendar not match the Gregorian one? What day number are you trying to change? Can you provide a page that shows the problem?

**Comment by osamasaleh90** [comment]
i'd like to thank you for reply , i will give you live sample for my problem,
today "Sunday" in Gregorian date is 03-06-2018 in Hijri date is 18-09-1439
but when i used umm alqura clendar , hijri date is come to be 19-09-1439 sunday
so i need something to add or subtract days from hijri date to reach my goal

**Comment by diassynthesis** [comment]
The problem ???
[Difficult to Predict](https://www.timeanddate.com/calendar/islamic-calendar.html)

The traditional version of the Islamic calendar requires an authorized person or committee to make an actual sighting of the Crescent Moon to determine the length of each month.

This dependence on astronomical observations makes it difficult to predict the length of Islamic months. Clouds and other adverse atmospheric conditions can obscure an otherwise visible Crescent Moon. When this happens, the new month will begin a day later, at short notice.

As an example (go to this site : [https://www.islamicfinder.org/islamic-date-converter/](url)

![islamiccalendar1](https://user-images.githubusercontent.com/3822648/40891587-319f38d4-6780-11e8-985f-134ac42890e9.png)

![islamiccalendar2](https://user-images.githubusercontent.com/3822648/40891605-877b8fa0-6780-11e8-8de2-52681f139415.png)



I think this is why we need to adjust the date manually (as stated by osamasaleh90)

**Comment by kbwood** [comment]
The version of the Islamic calendar provided here is the '16 civil' calendar - based on code from [http://www.iranchamber.com/calendar/converter/iranian_calendar_converter.php](http://www.iranchamber.com/calendar/converter/iranian_calendar_converter.php). It is a calculated form of the calendar as it is not practical to incorporate the visual sightings each year. If this is not sufficient for your purposes then you are free to implement a more accurate version.

**Comment by osamasaleh90** [comment]
thanks for all

![screenshot 7 _li](https://user-images.githubusercontent.com/39797324/40913361-ab6e813c-67f4-11e8-972c-9fac6bdd68d6.jpg)
in previous attached image today monday is 20th 
i just need to change date from monday 20th to 19th
like microsoft calendar offset option in next attachment
![screenshot 12](https://user-images.githubusercontent.com/39797324/40914095-29e96c6e-67f7-11e8-9be3-2cba7fe595e0.png)
![screenshot 10](https://user-images.githubusercontent.com/39797324/40914101-2ebd6984-67f7-11e8-9887-4b45f17000e4.png)

**Comment by diassynthesis** [comment]
@osamasaleh90 if i understand, the **conversion** part of the **jQuery Calendars** is unusable (at least for the Islamic Calendar) until we can find a way to adjust this offset.

Between time, can you take **[this](http://keith-wood.name/calendars.html#add)** into consideration 

![jquerycalendars](https://user-images.githubusercontent.com/3822648/40929680-6bcf6144-681d-11e8-88dd-40807daab80f.PNG)

Best regards.
